// lerna/packages/app/src/components/Header/Header.jsx
import React from "react";
import styled from "styled-components/macro";

import StyledTitle from "../Title";

import { DEFAULT_PADDING } from "../../css.settings";

const Title = styled(StyledTitle).attrs((props) => ({
  ...props,
  forwardAs: "h1",
  size: 2,
}))`
  text-transform: lowercase;
  color: #fff;
`;

const Wrapper = styled.header`
  min-height: 120px;
  align-items: center;
  display: flex;
  flex-direction: column;
  justify-content: center;
  background-color: ${(props) => props.theme.palette.primaryColor};
  padding: ${DEFAULT_PADDING};
`;

const Header = () => (
  <Wrapper>
    <Title>Front-end boilerplate</Title>
  </Wrapper>
);

export default Header;

// vuejs/src/components/Header.vue
<template>
  <header class="header">
    <div class="heder-left-area">
      <Title class="header-title">VueJS boilerplate</Title>
    </div>
    <div class="heder-right-area"></div>
  </header>
</template>

<script>
import Title from "./Title";

export default {
  components: {
    Title,
  },
};
</script>

<style lang="scss" scoped>
.header {
  align-items: center;
  display: flex;
  justify-content: space-between;
  background-color: #e62429;
  padding: 15px;
  min-height: 80px;
}

.header-title {
  color: #fff;
}
</style>
